using Core.Dtos.RControl.ClinicalGroups;

namespace Application.Queries.RControl.ClinicalGroups.GetTreatmentComplexityCoefficientsQuery;

public sealed record GetTreatmentComplexityCoefficientsResult(IReadOnlyCollection<TreatmentComplexityCoefficientDto> TreatmentComplexityCoefficients);
