namespace Core.Dtos.RControl.Categories.MedicalCase;

public sealed record MedicalCaseDetailsDto(
    int MedicalProfile,
    int PhysicianSpecialty,
    DateTime TreatmentStartDate,
    DateTime TreatmentEndDate,
    string PrimaryDiagnosis,
    decimal? PaidUnits,
    string? Department,
    long? DepartmentCode,
    bool IsPediatric,
    string? VisitPurpose,
    int? BedProfile,
    string MedicalRecordNumber,
    bool? IsAdmissionTransfer,
    bool? IsRehabilitation,
    int? HospitalizationDuration,
    string? FacilityLevel,
    string? InitialDiagnosis,
    bool? IsOncologySuspicion,
    string PhysicianCode,
    decimal? Weight,
    byte? DiseaseCharacter,
    string? InternalComment);
