using Core.Dtos.MedView.Filters;

namespace Application.Queries.MedView.Filters.GetInsurancePolicyTypeFilterOptionsQuery;

public sealed record GetInsurancePolicyTypeFilterOptionsResult(IReadOnlyCollection<InsurancePolicyTypeFilterOptions> Options);
